language: go
sudo: true

services:
  - docker

matrix:
  allow_failures:
    - os: windows
    - go: master
  include:
    # Linux
    - os: linux
      go: 1.14.x
      cache:
        directories: ["$HOME/.cache/go-build", "$GOPATH/pkg/mod"]
    - os: linux
      go: master
    # macOS
    - os: osx
      go: 1.14.x
      cache:
        directories: ["$HOME/Library/Caches/go-build", "$GOPATH/pkg/mod"]
    # Windows
    - os: windows
      go: 1.14.x
      cache:
        directories: ["C:\\Users\\travis\\AppData\\Local\\go-build"]

before_install:
  # Setup directory for binaries
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # Install 'make' and dependencies on Windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi

before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
  - go mod graph

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker
  - make test-integration && make clean-integration

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: S/CFrglarZ42a3crv+GgWSPZrPjIJglk1exzjbcP5KoPVinuucRxfQW/+92pfOSGTK2XZA1N20ZZE7+ba7HlWXkJDiICew8hCKHkDMW1Rj+E89zwzJMURXxDPTUkecE3h7BwSv72+XqQiezBo2HW5cPecQo3bmuhlmJO0ja9ntzhSpXTr1lcpBDIWvxHGzLR/Dcoceki3PI/nbv4i9ZVoUFtx9f/bbCQ7S/7qX6Dn5WKSjoEIvMgwtuAptYbEeDZ51mmudAuMAduNQpXJKiUUeryokP3sEP6FcwP7oKy6b7Dk92l1Q7MJ7lLj0xRcWIty5YCx1jKy5L/EKPLFinYdCJVyI1e11sF2YLvlzC3tsbOJHDgA2W4brt3hBfTW23FXgVJBAfKsCmwzcMrtR3WC0ukcwdTBva/oCIZUBkw0M2d4rDBgWLQ6vKtuCrn2WOlDTEVSyfzSxOSBdcLCgTeDELwdCW8nniuW9ldVUYotwDy/v9RljzOsb+dUwBtbagtXeQ2nraPWJnj8zHAkMQS11/FxxOQ53W5BQQGAEbeUIbwi5P4EJCHip70IqVKPkkWtPo3iVUyR7C4m0TkgA3L47PV/t8o4alvdHbhyP+DKYalQkdLiZSlFTMjavmXVO4ofhTHNAfz2LkemF8gcBiXQxpsBrUc5j+gi+nG3mfAgrE=
  file_glob: true
  file:
    - bin/ach*
  on:
    tags: true
    repo: moov-io/ach
    go: 1.14.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: CbBIBY8jTuRNyBSv2JvsKzYeTdS1HBpwqqOTPeljHE2QL9u0h+Ji0yR+n1w3QqbzKurRjcKKs6mLgqy7Gmj40FXOxhro1icFMN9dapbwUanxwOzIicTVz1DqwlkB5KLMpVY6LYU4zAOusA7zpRkfORV18LiHYwS3332qtpnJU7I8rPh4JKxAR1oEwpl0KBjQQ0S5Nuo8xDcADjlAA2I6nw3Jz48Pynq5tEnNr99iXNmbOrIgHbVRaquZ+8t7N2V0mI5+9X1GRWnx8Z7hkcECvSMmDw7uZH3HF4yMp+XolAT2CRuz1H19LDZK1FPHCxc8FW9ApJcIrJaDal0/5W4H0jJ3Nhr2U2A0N90uaaDchizjOkYLkcYXtBSREqY6wOcXVWiMsTU8eEDDveAh/t0yKJSnQRcg3ePY924HsHI2H0yzxDu1LSaWH85dV/qIfV6oyvYYFdDrhzDJqWrwdwEu1Yqnc/nKsXV84uxyWDLJ36iyHG3yPb1qv6jPodteG/G2iS78lQicgZkPSgc8z1DHuHFAbagHiBbze5UrHTP6OJpAjyUWGJSe0hcrbBqRl+f410OuvpIEJr8U63luGMkrV6GuODPTLfLOWCfA1E1/RDA3NitTq1Ep5pmzOSta9Bmpm2fbl58Sp46Z9Nta/Sq8UMufxcq1ayJtwg6nd9F1iRE=
